name: dependencies
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  
  # Core
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  url_launcher: ^6.0.2
  get_it: ^6.0.0
  lottie: ^1.0.1

  # UI
  package_info: ^2.0.0